Specify a single semver-compatible range for each dependency
The dependencies specified in this project's Cargo.toml are problematic
for at least 3 reasons.

- A dependency like `clap = ">=3.2.25"` means "uefisettings is
  compatible with every unreleased future version of clap, including v5,
  v6, v7, etc". That is unknowable but very likely false.

- When this project is pulled in as a dependency into a larger Cargo
  workspace, the versions Cargo assigns for uefisettings's dependencies
  will flap unpredictably, for example between thiserror v1 and v2,
  leading to spurious and confusing diffs.

- Uefisettings declares compatibility with crate versions that it is
  definitely not compatible with. For example `binrw = ">=0.10"` is
  listed as a dependency, but uefisettings definitely does not work when
  compiled against binrw 0.10. This means if someone has a project using
  binrw 0.10, and they add a dependency on uefisettings, uefisettings
  will fail to compile instead of pulling in the actual binrw dependency
  it needs.

      error[E0107]: associated type takes 0 lifetime arguments but 1 lifetime argument was supplied
          --> src/lib/hii/forms.rs:1393:29
           |
      1393 |     for<'a> <T as BinRead>::Args<'a>: Default,
           |                             ^^^^---- help: remove the unnecessary generics
           |                             |
           |                             expected 0 lifetime arguments
           |
      note: associated type defined here, with 0 lifetime parameters
          --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binrw-0.10.0/src/binread/mod.rs:50:10
           |
      50   |     type Args: Clone;
           |          ^^^^

In this PR I have matched the versions currently captured in Cargo.lock.
For example I am changing `binrw = ">=0.10"` to `binrw = "0.13"` because
according to the lockfile that is what uefisettings in this repo
currently builds against.

Signed-off-by: David Tolnay <dtolnay@gmail.com>